--- #YAML:1.0
name:               Finance-Card-Discover
version:            0.04
abstract:           DiscoverCard account information and SOAN creation
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.82
requires:
    Crypt::SSLeay:   0
    DateTime::Tiny:  0
    LWP::UserAgent:  0
    Object::Tiny:    0
    URI:             1.36
    XML::LibXML:     0
resources:
    repository:  http://github.com/gray/finance-card-discover
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
