--- #YAML:1.0
name:               Finance-Card-Discover
version:            0.05
abstract:           DiscoverCard account information and SOAN creation
author:
    - gray <gray@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.82
requires:
    DateTime::Tiny:       0
    LWP::Protocol::https:  6.02
    LWP::UserAgent:       6.02
    Object::Tiny:         0
    URI:                  1.36
    XML::LibXML:          0
resources:
    repository:  http://github.com/gray/finance-card-discover
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
